pre-release-hook = [
    "git-cliff",
    "-v",
    "-c",
    "../cliff.toml",
    "-r",
    "../",
    "-t",
    "{{tag_name}}",
    "-p",
    "CHANGELOG.md",
    "--unreleased",
    "{{crate_name}}-v{{prev_version}}..HEAD",
]
