name: release and publish
on:
    workflow_dispatch:
        inputs:
            bump_level:
                description: "The bump level of this release"
                required: true
                type: choice
                options:
                    - alpha
                    - beta
                    - rc
                    - release
                    - patch
                    - minor
                    - major
            overwrite_version:
                description: "Overwrite the version for this release"
                required: false
                type: string
env:
    REGISTRY: "ghcr.io"
    IMAGE_NAME: "pwnhub-bot"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install git-cliff
              uses: actions-rs/install@v0.1
              with:
                  crate: git-cliff
                  version: latest
            - name: install cargo-release
              uses: actions-rs/install@v0.1
              with:
                  crate: cargo-release
                  version: latest
            - name: run cargo-release
              run: |
                  OVERWRITE=${{ inputs.overwrite_version }}
                  BUMP_LEVEL=${OVERWRITE:-${{ inputs.bump_level}}}
                  cargo release --verbose --execute --no-verify --no-publish --workspace $BUMP_LEVEL
