name: release and publish
on:
    workflow_dispatch:
        inputs:
            bump_level:
                description: "The bump level of this release"
                required: true
                type: choice
                options:
                    - alpha
                    - beta
                    - rc
                    - release
                    - patch
                    - minor
                    - major
            overwrite_version:
                description: "Overwrite the version for this release"
                required: false
                type: string
env:
    REGISTRY: "ghcr.io"
    IMAGE_NAME: "pwnhub-bot"
jobs:
    release:
        environment: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: load gpg key used to sign commits
              uses: crazy-max/ghaction-import-gpg@v5

              with:
                  gpg_private_key: ${{ secrets.PGP_SIGNING_SUBKEY }}
                  git_user_signingkey: true
                  fingerprint: 97846C8651A44F47
                  git_commit_gpgsign: true
                  git_tag_gpgsign: true
                  # not supported by github
                  git_push_gpgsign: false
            #- name: set git user and email and signing key
            #  run: |
            #      git conifg user.signingkey 97846C8651A44F47
            #      git config commit.gpgsign true
            #      git config user.name PwnHub Release
            #      git config user.email release@pwnhub.club
            - name: install git-cliff
              uses: baptiste0928/cargo-install@v1
              with:
                  crate: git-cliff
                  version: latest
            - name: install cargo-release
              uses: baptiste0928/cargo-install@v1
              with:
                  crate: cargo-release
                  version: latest
            - name: run cargo-release
              run: |
                  OVERWRITE=${{ inputs.overwrite_version }}
                  BUMP_LEVEL=${OVERWRITE:-${{ inputs.bump_level}}}
                  cargo release --verbose --execute --no-verify --no-publish --no-confirm --workspace $BUMP_LEVEL
